# error
error对象编程时是最常见的一个错误类型
```go
//演示的如果使用调用方法时返回的error对象
func main() {
	str := "12a"
	if ret, err := strconv.Atoi(str); err != nil {
		fmt.Println(err)
	} else {
		fmt.Printf("%T", ret)
	}
}
```

```go
//演示自己构造一个error对象，并使用
func main() {
	_, err := add(-1, 2)
	if err != nil {
		fmt.Println(err)
	}
}

func add(i, j int) (int, error) {
	if i < 0 {
		return 0, errors.New("i不能小于0")//通过errors.New()方式初始化一个error对象
	}
	return 1 + j, nil
}
```
# 运行时错误
一些运行时异常（比如:1/0）会导致程序运行中断，当然也可以自己通过panic(msg string)方法构造一个运行时异常。  
有点类似java/C#中的throw
```go
func add(i, j int) int {
	if i < 0 {
		panic("i值不能小于0")
	}
	i = j / i
	return 1 + j
}
```
# 恢复
当程序发生运行时异常时，可以通过调用recover()方法来恢复，避免程序中断波及方法调用方。  
recover()的调用通常结合defer关键字使用（在方法结束时执行）
```go
func add(i, j int) int {
	defer func() {
		if err := recover(); err != nil {
			fmt.Println(err)
		}
	}()
	if i < 0 {
		panic("i值不能小于0")
	}
	i = j / i
	return 1 + j
}
```